# Generated by Django 3.0.4 on 2020-04-02 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='subscribed_users',
        ),
        migrations.AddField(
            model_name='newsletter',
            name='description',
            field=models.TextField(max_length=2000, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='title',
            field=models.CharField(max_length=50, null=True, verbose_name='title'),
        ),
    ]
