# Generated by Django 3.0.4 on 2020-04-02 11:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0002_auto_20200402_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookstore',
            name='timestamp',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookstore',
            name='updated',
            field=models.DateField(auto_now=True),
        ),
    ]
